# example netlify.toml
[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = "/dist"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

[context.production]
    command = "yarn run build"
    NODE_ENV = "production"
[content.branch-deploy]
    command = "yarn run deploy-preview"
    NODE_ENV = "production"

[dev]
port = 3000 # Port that the dev server will be listening on
publish = "dist" # Folder with the static content for _redirect file
command = "yarn start-netlify-dev" # Command to start your dev server
targetPort = 1234
NODE_ENV = "development"

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from = "/update"
  to =  "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/"
  to = "https://doctoranytime.gr/"
  force = true
  conditions = {Country=["gr"]}

[[redirects]]
  from = "/"
  to = "https://doctoranytime.be/"
  force = true
